### ISSUE TITLE
dose-response of difference in means

### ISSUE THREAD

**Issue by fmmattioni** [alecri/dosresmeta#1]
Dear Dr. Crippa,

Thank you very much for your R package! I am currently trying to modify it to fit in my purposes. I am conducting a dose-response meta analysis in RCTs. Each RCT have two interventions, and I am looking at the change between pre- and post- intervention. Therefore, I have one data point for each intervention in each study. What would be the most appropriate way of using the one-stage approach to fit a dose-response curve of difference in means (pre vs post) for all the studies combined with your dosresmeta package?

Best,

Felipe

**Comment by alecri** [comment]
Hi Felipe, where is the dose-response part in your data? Maybe you could put some example data.
/Alessio

**Comment by fmmattioni** [comment]
Hello Dr. Crippa,

I have just realized all I had to do was selecting the procedure to be "1stage" when conducting the analysis. It worked perfectly! I was wondering now how I could test if there is a statistical difference between the two dose-response curves (intervention1 vs intervention2)? I am also having problems when conducting the sensitivity analysis, it seems that I am not getting unique knots.

I have created a repository with an example of the data (https://github.com/fmmattioni/data). These are mean changes in maximal oxygen uptake across different doses of MET-h/week.

Thank you in advance,

Felipe

**Comment by alecri** [comment]
Can you put also the code that you run and specify the question you're interested in?
Alessio

**Comment by fmmattioni** [comment]
Please, find below the code I am running it. It was based on the code you posted from the paper. I cannot make the sensitivity analysis work, all the rest seems to be working quite well.

Basically, our research question is: what is the dose-response relationship of _intervention1_ versus _intervention2_ on improvements in maximal oxygen uptake?

The code:

### Dose-response meta-analysis of difference in means ###


# Loading packages
library(dosresmeta)
library(rms)
library(mvtnorm)
library(DoseFinding)
library(aod)

## Loading data 
load("intervention1.RData")

## Auxiliary function to estimate target doses (to be implemented in dosresmeta pkg)
doseEff <- function(p, dose, Ep, trunc = FALSE){
  max <- max(Ep)
  EDmax <- dose[which.min(abs(Ep - max))]
  if (trunc == TRUE){
    if (EDmax == max(dose)) return(data.frame(p = NA, ED = NA, Ep = NA))      
  }
  ED <- apply(matrix(p), 1, function(x)
    dose[which.min(abs(Ep[dose < EDmax] - x * max(Ep)))])
  
  data.frame(p, ED, Ep = p * max(Ep))
}

## ----------------------------------------------------------------
## Main analysis
  knots <- quantile(intervention1$dose, c(.1, .5, .9))

## Obtaining mean differences, variances, and (co)varinace matrices for the all the studies
  cov.md <- by(intervention1, intervention1$id, function(x) covar.smd(y, sd, n, "md", data = x))
  intervention1$md <- unlist(lapply(cov.md, function(x) x$y))
  intervention1$vmd <- unlist(lapply(cov.md, function(x) x$v))

spl <- dosresmeta(formula = y ~ rcs(dose, knots), id = id, sd = sd, n = n, 
                  covariance = "md",method = "reml",proc = "1stage", data = intervention1)

## Summary of the model, print coefficients and covariance matrix
summary(spl)
round(coef(spl), 3)
round(vcov(spl), 2)

## Tabular prediction
newdata <- data.frame(dose = seq(0, 18, by = 2))
pred_md <- predict(spl, newdata = newdata, xref = 0, expo = FALSE)
round(pred_md, 2)

## Target doses with 'confidence interval'
p <- c(.5, .8, 1)
newdata <- data.frame(dose = seq(0, max(intervention1$dose), length.out = 5000))
edp <- with(predict(spl, newdata), 
            doseEff(p = p, dose = newdata$dose, Ep = pred, trunc = FALSE))
round(edp, 2)

set.seed(1234)
mvsample <- rmvnorm(10000, mean = coef(spl), vcov(spl))
results <- do.call("rbind", apply(mvsample, 1, function(y){
  pred <- rcs(newdata$dose, knots) %*% y
  doseEff(p = p, dose = newdata$dose, Ep = pred, trunc = F)
}))
by(results, results$p, function(x) 
  round(quantile(x$ED, c(.025, .975), na.rm = T), 2))



## -----------------------------------------------------------------------------
## Sensitivity analysis

## 1) Location of knots
knlist <- combn(quantile(intervention1$dose, c(.1, .25, .5, .75, .9)), 3, simplify = F)[-c(1, 10)]
#do.call(rbind, knlist)
modi_k <- lapply(knlist, function(k)
  dosresmeta(formula = y ~ rcs(dose, k),
             sd = sd, n = n, covariance = "md", method = "reml",proc = "1stage", data = intervention1)
)

**Comment by alecri** [comment]
Sorry for the late reply. From what I understood, you want to compare if two curves are different, and this can be done with a meta-regression model. Find the script below with some comments.

library(dosresmeta)
library(tidyverse)
library(rms)
library(mvtnorm)
library(DoseFinding)

### create just one data set
load("intervention1.RData")
load("intervention2.RData")
dat <- rbind(
  cbind(intervention1, intervention = "First"),
  cbind(intervention2, intervention = "Second") %>%
    mutate(id = id + max(intervention1$id))
)

doseEff <- function(p, dose, Ep, trunc = FALSE){
  max <- max(Ep)
  EDmax <- dose[which.min(abs(Ep - max))]
  if (trunc == TRUE){
    if (EDmax == max(dose)) return(data.frame(p = NA, ED = NA, Ep = NA))
  }
  ED <- apply(matrix(p), 1, function(x)
    dose[which.min(abs(Ep[dose < EDmax] - x * max(Ep)))])
  
  data.frame(p, ED, Ep = p * max(Ep))
}

## main analysis
knots <- quantile(dat$dose, c(.1, .5, .9))
spl <- dosresmeta(formula = y ~ rcs(dose, knots), id = id, sd = sd, n = n,
                  covariance = "md", data = dat, proc = "1stage", 
                  mod = ~ intervention)
summary(spl)

### test for differences in the curves according to intervention
waldtest(vcov(spl), coef(spl), 3:4)

## graphical and tabular prediction
newdata <- expand.grid(dose = seq(0, 18, by = .5), intervention = c("First", "Second"))
pred_md <- cbind(newdata, predict(spl, newdata = newdata, xref = 0, expo = FALSE))

ggplot(pred_md, aes(dose, pred, linetype = intervention)) +
  geom_line() +
  theme_classic()

pred_md %>%
  select(dose, intervention, pred, ci.lb, ci.ub) %>%
  filter(dose %in% seq(0, 18, by = 2)) %>%
  print(digits = 2)


## Target doses with 'confidence interval'
p <- c(.5, .8, 1)
newdata <- expand.grid(dose = seq(0, max(dat$dose), length.out = 5000), 
                      intervention = c("First", "Second"))
edp1 <- with(predict(spl, subset(newdata, intervention == "First")),
            doseEff(p = p, dose = newdata$dose, Ep = pred, trunc = FALSE))
edp2 <- with(predict(spl, subset(newdata, intervention == "Second")),
             doseEff(p = p, dose = newdata$dose, Ep = pred, trunc = FALSE))
round(edp1, 2)
round(edp2, 2)

set.seed(1234)
mvsample <- rmvnorm(10000, mean = coef(spl), vcov(spl))
mvsample1 <- mvsample[, 1:2]
mvsample2 <- mvsample1 + mvsample[, 3:4]
newdata <- data.frame(dose = seq(0, max(dat$dose), length.out = 5000))
results1 <- do.call("rbind", apply(mvsample1, 1, function(y){
  pred <- rcs(newdata$dose, knots) %*% y
  doseEff(p = p, dose = newdata$dose, Ep = pred, trunc = F)
}))
results2 <- do.call("rbind", apply(mvsample2, 1, function(y){
  pred <- rcs(newdata$dose, knots) %*% y
  doseEff(p = p, dose = newdata$dose, Ep = pred, trunc = F)
}))
by(results1, results1$p, function(x)
  round(quantile(x$ED, c(.025, .975), na.rm = T), 2))
by(results2, results2$p, function(x)
  round(quantile(x$ED, c(.025, .975), na.rm = T), 2))

## sensitivity analysis
quantile(dat$dose, c(.1, .25, .5, .75, .9))
### the 10% and 25% percentiles are the same.
### you can exclude the 25% percentile from the sensitivity analysis
quantile(dat$dose, c(.1, .5, .75, .9))
### or exclude the 0 doses
quantile(dat$dose[dat$dose > 0], c(.1, .25, .5, .75, .9))

knlist <- combn(quantile(dat$dose, c(.1, .5, .75, .9)), 3, simplify = F)[-c(1, 10)]
knlist <- combn(quantile(dat$dose[dat$dose > 0], c(.1, .25, .5, .75, .9)), 3, simplify = F)[-c(1, 10)]
modi_k <- lapply(knlist, function(k)
  dosresmeta(formula = y ~ rcs(dose, k), id = id, sd = sd, n = n,
             covariance = "md", data = dat, proc = "1stage", 
             mod = ~ intervention))

**Comment by fmmattioni** [comment]
Dear Alessio,

That is fantastic. This is precisely what I needed!

All the best,

Felipe
